import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { inventory } from '../data/inventory.js'
import Products from '@/components/products/index.js'
import { useState } from 'react'


export default function Home() {

  const [productInventory, setProductInventory] = useState({...inventory});

  const [gender, setGender] = useState();
  const [category, setCategory] = useState();

  return (
    <>
      <Head>
        <title>CHANGE ME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.leftCol}>
          <div className={styles.filterContainer}>
            <div className={styles.categoryHeader} onClick={() => {setGender("Male"); setCategory(null);}}>Male</div>
            <div className={styles.category} onClick={() => {setGender("Male"); setCategory("Hoodies");}}>Hoodies</div>
            <div className={styles.category} onClick={() => {setGender("Male"); setCategory("Jackets");}}>Jackets</div>
            <div className={styles.category} onClick={() => {setGender("Male"); setCategory("Headgear");}}>Headgear</div>
            <div className={styles.categoryHeader} onClick={() => {setGender("Female"); setCategory(null);}}>Female</div>
            <div className={styles.category} onClick={() => {setGender("Female"); setCategory("Hoodies");}}>Hoodies</div>
            <div className={styles.category} onClick={() => {setGender("Female"); setCategory("Jackets");}}>Jackets</div>
            <div className={styles.category} onClick={() => {setGender("Female"); setCategory("Headgear");}}>Headgear</div>
            <div className={styles.categoryHeader} onClick={() => {setGender("Unisex"); setCategory(null);}}>Unisex</div>
            <div className={styles.category} onClick={() => {setGender("Unisex"); setCategory("Hoodies");}}>Hoodies</div>
            <div className={styles.category} onClick={() => {setGender("Unisex"); setCategory("Jackets");}}>Jackets</div>
            <div className={styles.category} onClick={() => {setGender("Unisex"); setCategory("Headgear");}}>Headgear</div>
          </div>
        </div>
        <div className={styles.rightCol}>
          {
            productInventory.clothing && productInventory.clothing.map(( clothing, index ) => {
              if ( clothing.sex == gender && category == null ) {
                  return(
                      <>
                          <Products key={index} title={clothing.title} />
                      </>
                  )
              } else if ( clothing.sex == gender && clothing.category == category ){
                  return(
                      <>
                          <Products key={index} title={clothing.title} cost={clothing.cost} color={clothing.hex} />
                      </>
                  )
              }
            })
          }
        </div>
      </main>
    </>
  )
}
